######################################################################
# Automatically generated by qmake (2.01a) Wed Feb 18 15:00:17 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += helloQt.cpp
